print("Twinkle, twinkle, little star")
print("        How I wonder what You are!")
print("                Up above the world so high,")
print("                Like a diamond in the sky")
print("Twinkle, twinle, little star")
print("         How I wonder what You are")